version: '3'
services:
  database:
    image: postgres
    restart: always
    container_name: db-pg
    env_file:
      - database.env
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: service
    external_links: 
      - db-pg:db-pg
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    depends_on:
      - database
